name: {{name.snakeCase()}}
description: Neoflex {{name.snakeCase()}} template

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.0+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_language_fonts: ^2.0.0
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  local_auth: ^2.1.3
  reactive_forms: ^13.0.0
  retrofit: ^4.0.1  
  {{name.snakeCase()}}_core:
    path: ./packages/{{name.snakeCase()}}_core

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  process_run: ^0.12.5+2
  retrofit_generator: ^5.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
    - assets/icons/
    - .prod.env
    - .dev.env
