name: {{name.snakeCase()}}
description: Neoflex {{name.pascalCase()}} template

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  local_auth: ^2.3.0
  path_provider: ^2.1.4
  reactive_forms: ^17.0.1
  retrofit: ^4.2.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  {{name.snakeCase()}}_core:
    path: ./packages/{{name.snakeCase()}}_core
  {{name.snakeCase()}}_ui_kit:
    path: ./packages/{{name.snakeCase()}}_ui_kit
  super_banners: ^0.0.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.3.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  path: ^1.9.0
  process_run: ^1.1.0
  retrofit_generator: ^8.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
