name: {{name.snakeCase()}}
description: Neoflex {{name.snakeCase()}} template
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  app_runner: ^2.2.2
  auto_route: ^7.8.4
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  local_auth: ^2.1.7
  path_provider: ^2.1.2
  reactive_forms: ^16.1.1
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  {{name.snakeCase()}}_core:
    path: ./packages/{{name.snakeCase()}}_core
  {{name.snakeCase()}}_ui_kit:
    path: ./packages/{{name.snakeCase()}}_ui_kit
  super_banners: ^0.0.1
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  process_run: ^0.13.2
  retrofit_generator: ^8.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
    - .prod.env
    - .dev.env
    - .env   
