name: {{name.snakeCase()}}_core
description: {{name.pascalCase()}} Core
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.17.1
  device_info_plus: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter: null
