name: {{name.snakeCase()}}_core
description: {{name.pascalCase()}} Core
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  package_info_plus: ^3.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: 3.1.0

flutter: null
