name: {{name.snakeCase()}}_ui_kit
description: "{{name.pascalCase()}} UI-Kit"
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  cached_network_image: ^3.3.1
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
