name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: Neoflex {{#snakeCase}}{{name}}{{/snakeCase}} template

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.2.1
  cupertino_icons: ^1.0.2
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.11
  l: ^3.2.0
  flutter_secure_storage: ^5.0.2
  flutter_launcher_icons: ^0.9.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  auto_route_generator:
  retrofit_generator:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

