name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: Neoflex {{#snakeCase}}{{name}}{{/snakeCase}} template

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: 5.0.4
  collection: 1.16.0
  dartz: 0.10.1
  dio: 4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 6.1.0
  flutter_spinkit: 5.1.0
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  google_language_fonts: 2.0.0
  hydrated_bloc: 9.0.0
  intl: 0.17.0
  json_annotation: 4.7.0
  reactive_forms: 14.1.0
  retrofit: 3.3.1
    
dev_dependencies:
  auto_route_generator: 5.0.3
  build_runner: 2.3.2
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  json_serializable: 6.5.4
  retrofit_generator: 4.2.0
  very_good_analysis: 3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
