name: dependencies
description: "Shared dependencies package."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  collection: ^1.19.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.19.0
  reactive_forms: ^17.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0
